spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcoursecluster.cw94pdh.mongodb.net/${DB_NAME:webflux}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course